// SPDX-License-Identifier: LGPL-3.0-only

pragma solidity >=0.8.0;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "./utils/Ownable.sol";

/*
MMMMMMMMMMMMMMMMMMMXx:..      ..,:oxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMK;                .,cx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMx.                    .,lOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXc                        'lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWMNx;.                        ,dKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNOl;.                       .,c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWXOdl:,..                   .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kdl;'.               .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOdl;'.           ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl;.        'OWWNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXXXXXNN0xo:.     .,'''''',;coxOXWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWXKOxdolc:;,''''',,,,;;;::c;.                  .;oONMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMN0xl:,'..',;:cllc::;;,,''...                           .;xXMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNOl'..;coxxddolc;,'..                                        ,kNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWXd,.'lk0Odc,..                  .'             .cd:             .lXWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWWO, .l0Oc'.                  .':oOX0'            .oOl.              ,dKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMK,  ;k:                 .,:okKNWMMMX;                                 .kWMMMMMMMMMMMMMM
MMMMMMMMMMMMMO.  ..            .';ldOKWMMMMMMMMMWc                                 .xMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWk;.       ..':ldOKNWMMMMMMMMMMMMMMMx,.                              .oWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWKkxdddxO0XWMMMMMMMMMMMMMMMMMMMMMMKx,                             .oNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXl                            ,kNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.                        .:xXMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'                    .,cxKWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'                  .oKWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.                   .cOWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKk;                      .:OWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;.                         .:OWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,                             .:0WMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.                                .oXMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'                                    ;0WMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;                             '.        'OWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.                       ',     :c  ..     ,KMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx.                         ,o'    lx.  ::    .kMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.                          .xd.  .xx.  'kl   ,KMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWo.                            :0d..c0c   .dNx,;kWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOlc:.                              ;O00Ol.    oWMWWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWx.                                   .',.      oWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWNx:,.                       .;.                   .xMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMk.                           'oo.                 ,KMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMK:                            .xO,               .xWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMW0,                             '0k.             .oNWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWd.                              oX;            'xWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNxc,.                           lX:           ;KWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:                           o0'           .OMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdcc,                      .ko             cXNNNWMMWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;                     .ll:,.          ..''',:ld0WMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;                       .;:;,.                .dNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'                        .,:;.              .lNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo:,...                   .o0xddddooooooddkKWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOkxdol:;,'.........':o0MMWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
*/

contract TheWhiteRabbit is ERC721URIStorage, Ownable {
    constructor(
        string memory _name, 
        string memory _symbol,
        string memory _tokenURI
    ) ERC721(_name, _symbol) {
        _mint(msg.sender, 1);
        _setTokenURI(1, _tokenURI);
    }

    function followTheWhiteRabbit() public pure returns (string memory) {
        return "secp256k1 {iv: \'6facd38562f4e6f099b5a7b580b2c5b5\', ephemPublicKey: \'04a0ac5d87f521962b7c5af4a676dcf71e187744dfe1a34720868f780b54b4e015daa98e9d1590f48e9675d59133c14c4c28a501dc89f0a1b97d654877b148dc2c\', ciphertext: \'aabcc79b9263a422222306713e41bb6155835db58b79de0564e212feb9ba59220e5cbaa5f59a980a710c0141a146bc52\', mac: \'89fdc2647a4cbd4ee4cc31179f907db62c67e6d306bb2f746199b0b5ac914602\'}";
    }

    function mint(uint256 id, string memory _tokenURI) external onlyOwner {
        _mint(msg.sender, id);
        _setTokenURI(id, _tokenURI);
    }

    function theDataWeCall(bytes calldata data) external onlyOwner {}
}
