// SPDX-License-Identifier: LGPL-3.0-only

pragma solidity >=0.8.0;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "./utils/Ownable.sol";

/*
MMMMMMMMMMMMMMMMMMMXx:..      ..,:oxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMK;                .,cx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMx.                    .,lOXWMMMMMMMMMMM939137977816a11d072ec2ec95105407MMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXc                        'lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWMNx;.                        ,dKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNOl;.                       .,c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWXOdl:,..                   .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kdl;'.               .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOdl;'.           ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl;.        'OWWNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXXXXXNN0xo:.     .,'''''',;coxOXWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWXKOxdolc:;,''''',,,,;;;::c;.                  .;oONMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMN0xl:,'..',;:cllc::;;,,''...                           .;xXMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNOl'..;coxxddolc;,'..                                        ,kNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWXd,.'lk0Odc,..                  .'             .cd:             .lXWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWWO, .l0Oc'.                  .':oOX0'            .oOl.              ,dKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMK,  ;k:                 .,:okKNWMMMX;                                 .kWMMMMMMMMMMMMMM
MMMMMMMMMMMMMO.  ..            .';ldOKWMMMMMMMMMWc                                 .xMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWk;.       ..':ldOKNWMMMMMMMMMMMMMMMx,.                              .oWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWKkxdddxO0XWMMMMMMMMMMMMMMMMMMMMMMKx,                             .oNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXl                            ,kNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.                        .:xXMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'                    .,cxKWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'                  .oKWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.                   .cOWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMM7f4c936b894b10d3c5e18d49632f2f1eMMMMMMMMMMMKk;                      .:OWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;.                         .:OWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,                             .:0WMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.                                .oXMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'                                    ;0WMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;                             '.        'OWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c.                       ',     :c  ..     ,KMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx.                         ,o'    lx.  ::    .kMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.                          .xd.  .xx.  'kl   ,KMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWo.                            :0d..c0c   .dNx,;kWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOlc:.                              ;O00Ol.    oWMWWWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWx.                                   .',.      oWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWNx:,.                       .;.                   .xMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMk.                           'oo.                 ,KMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMK:                            .xO,               .xWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMW0,                             '0k.             .oNWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWd.                              oX;            'xWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNxc,.                           lX:           ;KWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:                           o0'           .OMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdcc,                      .ko             cXNNNWMMWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;                     .ll:,.          ..''',:ld0WMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;                       .;:;,.                .dNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'                        .,:;.              .lNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo:,...                   .o0xddddooooooddkKWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOkxdol:;,'.........':o0MMWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
*/

contract TheWhiteRabbit is ERC721URIStorage, Ownable {

    string public followTheWhiteRabbit = "secp256k1 {iv: \'a4619e9bed3b91c7e2abad47d68d2003\', ephemPublicKey: \'04ad11798e70e60d6ff544190bc9dc18c877441886ef035281b2de00bed92cc5d911ba3f05276925199790bd227d350cb769f5f026d0f8183515cbba972d954ee5\', ciphertext: \'6cd8e6dd26158f9d343a1006bad2bddb3bb07e075d706ca0dcc348d1e0f2e410617639a331b57b5b105711dc42a9749d78286aab58c33c4de0e1f2347f81936ab80b436901c1a5234500e693ba8c097a5add5866e94d59a3266d4dd74a8cc67d\', mac: \'a3ec633d443896d051af8c69142403e757cb3cfeb478870d798ff2169028aa81\'}";
    
    constructor(
        string memory _name, 
        string memory _symbol,
        string memory _tokenURI
    ) ERC721(_name, _symbol) {
        _mint(msg.sender, 1);
        _setTokenURI(1, _tokenURI);
    }

    function mint(uint256 id, string memory _tokenURI) external onlyOwner {
        _mint(msg.sender, id);
        _setTokenURI(id, _tokenURI);
    }
}
